name: Check

on:
  workflow_call:

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: cargo test
  formatting:
    name: Run Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
  dependencies:
    name: Run Dependency Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-udeps
          toolchain: nightly
      - uses: actions-rs/cargo@v1
        with:
          command: udeps
          toolchain: nightly