name: Publish Image

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

permissions:
  packages: write
  contents: read

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Configure version
        run: |
          docker login docker.pkg.github.com --username ethankhall --password ${{ secrets.GITHUB_TOKEN }}
          docker run --rm -v $(pwd):/target docker.pkg.github.com/ethankhall/crom/cli:latest write-version custom ${{ inputs.version }}
      - name: Build local image
        run: |
          docker buildx build \
            --output=type=registry \
            --file Dockerfile \
            --tag docker.pkg.github.com/ethankhall/dev-null/dev-null:$(git rev-parse --short HEAD) \
            --tag docker.pkg.github.com/ethankhall/dev-null/dev-null:${{ inputs.version }} \
            .
