on:
  push:
    branches:
    - main

name: Release

permissions:
  contents: write
  packages: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: login to registry
        run: docker login docker.pkg.github.com --username ethankhall --password ${{ secrets.GITHUB_TOKEN }}
      - name: create release
        id: version
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          VERSION=$(docker run --rm -v $(pwd):/target docker.pkg.github.com/ethankhall/crom/cli:latest get next-release)
          gh release create $VERSION --generate-notes --prerelease --target $(git rev-parse HEAD) --draft
          echo "::set-output name=version::$VERSION"
  publish:
    uses: ./.github/workflows/create-artifacts.yml
    needs: create-release
    with:
      version: ${{ needs.create-release.outputs.version }}

  remove-draft:
    runs-on: ubuntu-latest
    needs:
      - create-release
      - publish
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: undraft release
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          gh release edit ${{ needs.create-release.outputs.version }} --draft=false

  tag-latest:
    runs-on: ubuntu-latest
    needs:
      - remove-draft
    steps:
      - name: Update latest tag
        run: |
          set -e
          docker login docker.pkg.github.com --username ethankhall --password ${{ secrets.GITHUB_TOKEN }}
          docker pull docker.pkg.github.com/ethankhall/dev-null/dev-null:${{ needs.create-release.outputs.version }}
          docker tag docker.pkg.github.com/ethankhall/dev-null/dev-null:${{ needs.create-release.outputs.version }} docker.pkg.github.com/ethankhall/dev-null/dev-null:latest
          docker push docker.pkg.github.com/ethankhall/dev-null/dev-null:latest

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: validate artifact
        run: docker build --target test .