on: [pull_request]

name: Continuous integration

permissions:
  contents: write
  packages: read

jobs:
  check:
    name: Run Validations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: validate artifact
        run: docker buildx build --target test .

  create-release:
    needs:
      - check
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: login to registry
        run: docker login docker.pkg.github.com --username ethankhall --password ${{ secrets.GITHUB_TOKEN }}
      - name: create pre-release
        id: version
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          VERSION=$(docker run --rm -v $(pwd):/target docker.pkg.github.com/ethankhall/crom/cli:latest get pre-release)
          gh release create $VERSION --generate-notes --prerelease --target $(git rev-parse HEAD) --draft
          echo "::set-output name=version::$VERSION"

  publish:
    uses: ./.github/workflows/create-artifacts.yml
    needs: create-release
    with:
      version: ${{ needs.create-release.outputs.version }}

  remove-draft:
    runs-on: ubuntu-latest
    needs:
      - create-release
      - publish
      - check
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: undraft release
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          gh release edit ${{ needs.create-release.outputs.version }} --draft=false
