on: [pull_request]

name: Continuous integration

permissions:
  contents: write
  packages: write
  pages: read
  

jobs:
  check:
    uses: ./.github/workflows/check-step.yml

  create-release:
    needs:
      - check
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: login to registry
        run: docker login docker.pkg.github.com --username ethankhall --password ${{ secrets.GITHUB_TOKEN }}
      - name: create pre-release
        id: version
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          VERSION=$(docker run --rm -v $(pwd):/target docker.pkg.github.com/ethankhall/crom/cli:latest get pre-release)
          gh release create $VERSION --generate-notes --prerelease --target $(git rev-parse HEAD) --draft
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  publish:
    uses: ./.github/workflows/create-artifacts.yml
    needs: create-release
    with:
      version: ${{ needs.create-release.outputs.version }}
      registry: ghcr.io/ethankhall/quorra-snapshot

  remove-draft:
    runs-on: ubuntu-latest
    needs:
      - create-release
      - publish
      - check
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: undraft release
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          gh release edit ${{ needs.create-release.outputs.version }} --draft=false

  docs:
    uses: ./.github/workflows/gh-pages.yml

  delete-failed:
    runs-on: ubuntu-latest
    needs:
      - check
      - create-release
      - publish
      - remove-draft
      - docs
    if: ${{ failure() && needs.create-release.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: delete draft release release
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          gh release delete ${{ needs.create-release.outputs.version }} --yes --cleanup-tag
